FROM openjdk:8u212-jre
MAINTAINER loafer 1218029121@qq.com
COPY ./target/febs-monitor-admin-1.0-SNAPSHOT.jar /febs/febs-monitor-admin-1.0-SNAPSHOT.jar
ENTRYPOINT ["java", "-Xmx256m", "-jar", "/febs/febs-monitor-admin-1.0-SNAPSHOT.jar"]
