server:
  port: 8301
spring:
  application:
    name: Gateway
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  boot:
    admin:
      client:
        url: http://localhost:8401
        username: febs
        password: 123456
  security:
    user:
      name: admin
      password: 123456
info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS


eureka:
  instance:
    lease-renewal-interval-in-seconds: 20
  client:
    register-with-eureka: true
    fetch-registry: true
    instance-info-replication-interval-seconds: 30
    registry-fetch-interval-seconds: 3
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8001/register/eureka/
zuul:
  routes:
    auth:
      path: "/auth/**"
      serviceId: cloud-auth
      sensitiveHeaders: "*"
    system:
      path: "/system/**"
      serviceId: service-system
      sensitiveHeaders: "*"
    test:
      path: "/test/**"
      serviceId: service-test
      sensitiveHeaders: "*"
  retryable: true
  ignored-services: "*"
  ribbon:
    eager-load:
      enabled: true
  host:
    connect-timeout-millis: 5000
    socket-timeout-millis: 5000

