server:
  port: 8301
spring:
  application:
    name: FEBS-Gateway
  boot:
    admin:
      client:
        url: http://${febs-monitor-admin}:8401
        username: febs
        password: 123456
  cloud:
    gateway:
      routes:
        - id: cloud-auth
          uri: lb://cloud-auth
          predicates:
            - Path=/auth/**
        - id: service-system
          uri: lb://service-system
          predicates:
            - Path=/system/**
        - id: service-test
          uri: lb://service-test
          predicates:
            - Path=/test/**
      default-filters:
        - StripPrefix=1

eureka:
  instance:
    lease-renewal-interval-in-seconds: 20
  client:
    register-with-eureka: true
    fetch-registry: true
    instance-info-replication-interval-seconds: 30
    registry-fetch-interval-seconds: 3
    serviceUrl:
      defaultZone: http://admin:123456@${febs-register}:8001/register/eureka/

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: health,info,gateway
