server:
  port: 8001
  servlet:
    context-path: /register
spring:
  application:
    name: FEBS-Register
  security:
    user:
      name: admin
      password: 123456
  boot:
    admin:
      client:
        url: http://${febs-monitor-admin}:8401
        password: 123456
        username: febs
info:
  app:
    name: ${spring.application.name}
    description: "微服务注册中心"
    version: "0.0.1-SNAPSHOT"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  instance:
    hostname: ${febs-register}
  client:
    register-with-eureka: false # 是否注册到微服务中心
    fetch-registry: false
    instance-info-replication-interval-seconds: 30 # 超时时间
    serviceUrl:
      # 服务器地址
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}${server.servlet.context-path}/eureka/
