FROM openjdk:8u212-jre
MAINTAINER loafer 1218029121@qq.com
COPY ./target/server-test-0.0.1-SNAPSHOT.jar /febs/server-test-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-Xmx256m", "-jar", "/febs/server-test-0.0.1-SNAPSHOT.jar"]
